# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eduard/projects/Chat/Chat_Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eduard/projects/Chat/Chat_Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduard/projects/Chat/Chat_Server/CMakeFiles /home/eduard/projects/Chat/Chat_Server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduard/projects/Chat/Chat_Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chat_Server

# Build rule for target.
Chat_Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Chat_Server
.PHONY : Chat_Server

# fast build rule for target.
Chat_Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/build
.PHONY : Chat_Server/fast

Chat.o: Chat.cpp.o
.PHONY : Chat.o

# target to build an object file
Chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat.cpp.o
.PHONY : Chat.cpp.o

Chat.i: Chat.cpp.i
.PHONY : Chat.i

# target to preprocess a source file
Chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat.cpp.i
.PHONY : Chat.cpp.i

Chat.s: Chat.cpp.s
.PHONY : Chat.s

# target to generate assembly for a file
Chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat.cpp.s
.PHONY : Chat.cpp.s

Chat_Server.o: Chat_Server.cpp.o
.PHONY : Chat_Server.o

# target to build an object file
Chat_Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat_Server.cpp.o
.PHONY : Chat_Server.cpp.o

Chat_Server.i: Chat_Server.cpp.i
.PHONY : Chat_Server.i

# target to preprocess a source file
Chat_Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat_Server.cpp.i
.PHONY : Chat_Server.cpp.i

Chat_Server.s: Chat_Server.cpp.s
.PHONY : Chat_Server.s

# target to generate assembly for a file
Chat_Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Chat_Server.cpp.s
.PHONY : Chat_Server.cpp.s

Get.o: Get.cpp.o
.PHONY : Get.o

# target to build an object file
Get.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Get.cpp.o
.PHONY : Get.cpp.o

Get.i: Get.cpp.i
.PHONY : Get.i

# target to preprocess a source file
Get.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Get.cpp.i
.PHONY : Get.cpp.i

Get.s: Get.cpp.s
.PHONY : Get.s

# target to generate assembly for a file
Get.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Get.cpp.s
.PHONY : Get.cpp.s

Hash.o: Hash.cpp.o
.PHONY : Hash.o

# target to build an object file
Hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Hash.cpp.o
.PHONY : Hash.cpp.o

Hash.i: Hash.cpp.i
.PHONY : Hash.i

# target to preprocess a source file
Hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Hash.cpp.i
.PHONY : Hash.cpp.i

Hash.s: Hash.cpp.s
.PHONY : Hash.s

# target to generate assembly for a file
Hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Hash.cpp.s
.PHONY : Hash.cpp.s

Message.o: Message.cpp.o
.PHONY : Message.o

# target to build an object file
Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Message.cpp.o
.PHONY : Message.cpp.o

Message.i: Message.cpp.i
.PHONY : Message.i

# target to preprocess a source file
Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Message.cpp.i
.PHONY : Message.cpp.i

Message.s: Message.cpp.s
.PHONY : Message.s

# target to generate assembly for a file
Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/Message.cpp.s
.PHONY : Message.cpp.s

User.o: User.cpp.o
.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i
.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s
.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chat_Server.dir/build.make CMakeFiles/Chat_Server.dir/User.cpp.s
.PHONY : User.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Chat_Server"
	@echo "... Chat.o"
	@echo "... Chat.i"
	@echo "... Chat.s"
	@echo "... Chat_Server.o"
	@echo "... Chat_Server.i"
	@echo "... Chat_Server.s"
	@echo "... Get.o"
	@echo "... Get.i"
	@echo "... Get.s"
	@echo "... Hash.o"
	@echo "... Hash.i"
	@echo "... Hash.s"
	@echo "... Message.o"
	@echo "... Message.i"
	@echo "... Message.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

